"""
1000+ Human-Style Topics for LinkedIn Posts
Topics organized by category - randomly selected for natural variety
"""

# ========================================
# PROGRAMMING & CODING
# ========================================
PROGRAMMING_TOPICS = [
    "প্রথম programming language কোনটা শেখা উচিত",
    "Python শিখে কি আসলেই job পাওয়া যায়",
    "JavaScript কেন এত জনপ্রিয়",
    "TypeScript কেন JavaScript এর থেকে better",
    "C++ শেখার দরকার কি আজকের দিনে",
    "Java কি আসলেই dead হয়ে যাচ্ছে",
    "Go language কেন এত hype হচ্ছে",
    "Rust programming এর ভবিষ্যৎ",
    "PHP কি সত্যিই dead",
    "Kotlin vs Java - কোনটা শিখবো",
    "Swift শেখা কি worth it বাংলাদেশে",
    "Ruby on Rails এখনও relevant কিনা",
    "C# এর demand কেমন market এ",
    "Functional programming কেন শেখা দরকার",
    "Object Oriented Programming কি আসলেই সব সমাধান",
    "Clean code লেখা কেন এত কঠিন",
    "Code review করার সময় কি কি দেখা উচিত",
    "Variable naming কেন এত important",
    "Comments লেখা কি really necessary",
    "Recursion বোঝা কেন এত কঠিন লাগে",
    "Data structures কেন শিখতে হবে",
    "Algorithm শেখা কি really দরকার job এ",
    "Big O notation কি কাজে লাগে real life এ",
    "SOLID principles কি follow করা দরকার সবসময়",
    "Design patterns কখন use করবো কখন করবো না",
    "প্রোগ্রামিং এ logic building কিভাবে improve করবো",
    "Competitive programming করা কি আসলেই দরকার",
    "LeetCode grind করা কি worth it",
    "HackerRank vs LeetCode কোনটা better",
    "Coding practice প্রতিদিন কতক্ষণ করা উচিত",
    "Programming শিখতে গিয়ে সবচেয়ে বড় ভুল",
    "Senior developer দের coding habit",
    "Junior থেকে Mid-level এ যেতে কি কি লাগে",
    "Code refactoring কখন করা উচিত",
    "Technical debt কি এবং কেন important",
    "Legacy code নিয়ে কাজ করার অভিজ্ঞতা",
    "Pair programming কি আসলেই কাজ করে",
    "Code smell কি এবং কিভাবে detect করবো",
    "DRY principle কি সবসময় follow করা উচিত",
    "KISS principle - Keep It Simple Stupid",
    "প্রোগ্রামিং এ ধৈর্য কেন সবচেয়ে বড় skill",
    "Debugging skills কিভাবে improve করা যায়",
    "Stack Overflow ছাড়া কি coding করা সম্ভব",
    "GitHub Copilot কি programmer দের replace করবে",
    "Regular expression কেন এত confusing",
    "API design করার best practices",
    "Error handling কেন ignore করা উচিত না",
    "Logging কেন important production এ",
    "Environment variables কেন hard code করা উচিত না",
    "প্রোগ্রামিং শেখার সময় কতটুকু theory কতটুকু practice",
    "Coding interview এ কি আসলে measure করা হয়",
]

# ========================================
# WEB DEVELOPMENT
# ========================================
WEB_DEV_TOPICS = [
    "React vs Next.js - কোনটা শিখবো",
    "Next.js 15 এর নতুন features",
    "Vue.js কেন underrated",
    "Angular কি এখনও worth learning",
    "Svelte কি React কে replace করবে",
    "Server Side Rendering কেন important",
    "Client Side Rendering vs SSR vs SSG",
    "CSS framework কোনটা ব্যবহার করবো",
    "Tailwind CSS কি CSS শেখার দরকার নেই",
    "Responsive design করার modern approach",
    "Web accessibility কেন ignore করা উচিত না",
    "SEO friendly website বানানোর tips",
    "Progressive Web Apps কি native app replace করবে",
    "Single Page Application এর pros and cons",
    "REST API vs GraphQL",
    "WebSocket কখন use করা উচিত",
    "Authentication implement করার best practices",
    "JWT vs Session based authentication",
    "OAuth 2.0 কিভাবে কাজ করে",
    "CORS কেন এত মাথা ব্যথার কারণ",
    "Web performance optimization techniques",
    "Lazy loading কিভাবে implement করবো",
    "Image optimization কেন important",
    "CDN কিভাবে website fast করে",
    "Caching strategy কি hona উচিত",
    "Browser DevTools এ কি কি আছে যেটা আমরা জানি না",
    "Web Components এর ভবিষ্যৎ",
    "Micro frontends কি এবং কখন দরকার",
    "Headless CMS কেন জনপ্রিয় হচ্ছে",
    "WordPress developer থেকে React developer হওয়ার journey",
    "Static site generators কখন use করবো",
    "Jamstack architecture কি",
    "Full stack development কি সত্যিই সব জানতে হয়",
    "Frontend developer দের কি backend শেখা উচিত",
    "Backend developer দের কি frontend জানা দরকার",
    "Web development এ career growth কেমন",
    "Freelancing এ web development এর demand",
    "E-commerce website বানানোর challenges",
    "Landing page design এর best practices",
    "Web development এর future কি",
    "HTMX কি নতুন revolution আনবে",
    "Astro framework কেন popular হচ্ছে",
    "Remix vs Next.js কোনটা better",
    "Vercel vs Netlify vs Railway deployment",
    "Supabase কি Firebase এর alternative হতে পারে",
    "State management কেন এত complicated",
    "Redux vs Zustand vs Context API",
    "React Query কেন game changer",
    "Form handling এর modern approach",
    "Dark mode implement করার best way",
]

# ========================================  
# BACKEND DEVELOPMENT
# ========================================
BACKEND_TOPICS = [
    "Node.js vs Python backend development",
    "Express.js কি এখনও best choice",
    "FastAPI কেন এত popular হচ্ছে",
    "Django vs Flask কোনটা শিখবো",
    "Spring Boot কেন enterprise এ dominant",
    "Microservices vs Monolith architecture",
    "API rate limiting কিভাবে implement করবো",
    "Database connection pooling কেন important",
    "Background job processing কিভাবে handle করবো",
    "Message queue কেন দরকার (RabbitMQ, Kafka)",
    "Redis কিভাবে application fast করে",
    "Caching strategies for backend",
    "Database indexing কেন important",
    "SQL vs NoSQL কখন কোনটা use করবো",
    "PostgreSQL vs MySQL কোনটা better",
    "MongoDB কি সব project এ use করা উচিত",
    "Database migration কিভাবে handle করবো",
    "ORM vs Raw SQL queries",
    "N+1 query problem কি এবং কিভাবে solve করবো",
    "API versioning best practices",
    "Pagination implement করার efficient way",
    "File upload handling best practices",
    "Email sending service কিভাবে setup করবো",
    "Payment gateway integration challenges",
    "Webhook কি এবং কিভাবে কাজ করে",
    "Server-sent events vs WebSocket",
    "gRPC কি REST API replace করবে",
    "Backend security best practices",
    "Input validation কেন critical",
    "SQL injection prevention কিভাবে করবো",
    "Rate limiting এবং throttling",
    "Backend monitoring tools",
    "Error tracking (Sentry, Datadog)",
    "Serverless functions কখন use করবো",
    "Lambda vs traditional server",
    "Backend developer দের common mistakes",
    "API documentation কেন important (Swagger/OpenAPI)",
    "Nginx কিভাবে কাজ করে",
    "Load balancing basics",
    "Horizontal vs vertical scaling",
    "Database sharding কি এবং কখন দরকার",
    "Connection timeout handling",
    "Retry mechanism implement করার best practices",
    "Idempotency কি এবং কেন important",
    "Event driven architecture",
]

# ========================================
# DEVOPS & CLOUD
# ========================================
DEVOPS_TOPICS = [
    "Docker কেন প্রতিটা developer এর শেখা উচিত",
    "Kubernetes কি সত্যিই দরকার",
    "CI/CD pipeline কিভাবে setup করবো",
    "GitHub Actions vs Jenkins",
    "AWS vs Azure vs GCP কোনটা শিখবো",
    "Cloud computing এর basics",
    "Infrastructure as Code কি",
    "Terraform কেন popular",
    "Linux command line কেন শিখতে হবে",
    "SSH কিভাবে কাজ করে",
    "DNS কিভাবে কাজ করে",
    "SSL/TLS certificate কি এবং কেন দরকার",
    "Nginx vs Apache",
    "Reverse proxy কি",
    "Container orchestration কেন দরকার",
    "Docker Compose দিয়ে local development",
    "Production deployment checklist",
    "Zero downtime deployment কিভাবে করবো",
    "Blue-green deployment strategy",
    "Monitoring এবং alerting setup",
    "Log management best practices",
    "Server security hardening",
    "Backup strategy কি হওয়া উচিত",
    "Disaster recovery plan",
    "Cloud cost optimization tips",
    "AWS Lambda দিয়ে serverless architecture",
    "S3 bucket management best practices",
    "CloudFront CDN setup",
    "VPC networking basics",
    "DevOps engineer vs SRE কি difference",
    "Platform engineering কি নতুন trend",
    "GitOps কি এবং কিভাবে কাজ করে",
    "Feature flags কেন use করবো",
    "Canary deployment strategy",
    "Observability vs monitoring difference",
    "Prometheus এবং Grafana দিয়ে monitoring",
]

# ========================================
# AI & MACHINE LEARNING
# ========================================
AI_ML_TOPICS = [
    "AI কি সত্যিই developer দের job খেয়ে ফেলবে",
    "ChatGPT কিভাবে আমাদের কাজ বদলে দিচ্ছে",
    "Claude vs ChatGPT কোনটা better",
    "AI coding assistants কিভাবে ব্যবহার করবো",
    "GitHub Copilot কি coding শেখার ক্ষতি করছে",
    "AI দিয়ে কি quality code লেখা সম্ভব",
    "Prompt engineering কেন important",
    "AI tools কোন কোনগুলো সত্যিই কাজের",
    "Cursor IDE কি VS Code replace করবে",
    "Vibe coding কি আসলে",
    "AI দিয়ে coding করা কি ভুল",
    "AI ব্যবহার করে productivity বাড়ানোর tips",
    "Machine Learning শেখা কি এখন mandatory",
    "Data Science vs Machine Learning vs AI difference",
    "LLM কিভাবে কাজ করে - simple explanation",
    "RAG (Retrieval Augmented Generation) কি",
    "Vector database কি এবং কেন দরকার",
    "Fine-tuning vs prompt engineering",
    "OpenAI API দিয়ে application বানানো",
    "Langchain কি এবং কিভাবে ব্যবহার করবো",
    "AI agent কি এবং কিভাবে কাজ করে",
    "AutoGPT এবং autonomous agents এর ভবিষ্যৎ",
    "AI ethics কেন important",
    "AI bias কি এবং কিভাবে avoid করবো",
    "AI এর কারণে rich আর poor এর gap বাড়ছে",
    "বাংলাদেশে AI adoption এর challenges",
    "AI subscription কেনার সামর্থ্য না থাকলে কি করবো",
    "Free AI tools যেগুলো paid এর কাছাকাছি",
    "AI দিয়ে content creation কি ethical",
    "AI generated code কি production ready",
    "Deepfake technology এর ভয়ঙ্কর ব্যবহার",
    "AI regulation কি দরকার",
    "Computer vision এর real world applications",
    "Natural Language Processing basics",
    "AI startups বাংলাদেশে",
    "ChatGPT Plus vs free version difference",
    "Claude Code কি এবং কিভাবে কাজ করে",
    "AI pair programming এর ভবিষ্যৎ",
    "Gemini vs ChatGPT vs Claude comparison",
    "AI tools দিয়ে কি freelancing করা যায়",
    "Model collapse কি - AI এর future risk",
    "AGI কি আসলে আসবে",
    "Sam Altman এবং OpenAI controversy",
    "Open source AI models (Llama, Mistral)",
    "Hugging Face কি এবং কেন important",
    "AI winter আসবে কি আবার",
    "বাংলাদেশের students রা কিভাবে AI শিখবে",
    "AI projects portfolio তে কিভাবে add করবো",
    "No-code AI tools কি developers দের threat",
    "Perplexity AI কি Google replace করবে",
]

# ========================================
# CAREER & JOB MARKET
# ========================================
CAREER_TOPICS = [
    "বাংলাদেশে software engineer দের salary কেমন",
    "Remote job কিভাবে পাবো বিদেশী company তে",
    "LinkedIn profile optimize করার tips",
    "Resume কিভাবে লিখলে interview call পাবো",
    "Portfolio website কি আসলেই দরকার",
    "GitHub profile কেন important job এর জন্য",
    "Networking কিভাবে করবো tech industry তে",
    "Referral কিভাবে পাবো big tech company তে",
    "Job switch কখন করা উচিত",
    "Salary negotiation কিভাবে করবো",
    "Counter offer accept করা কি ঠিক",
    "Notice period এ কি কি করা উচিত",
    "Probation period এ কি কি মাথায় রাখবো",
    "Tech lead হওয়ার জন্য কি কি দরকার",
    "Engineering manager vs Tech lead difference",
    "Staff engineer role কি",
    "Principal engineer কি করেন",
    "Architect role কি এবং কিভাবে হবো",
    "IC (Individual Contributor) vs Management track",
    "Career growth planning for developers",
    "T-shaped skills কি এবং কেন important",
    "Generalist vs Specialist developer",
    "বাংলাদেশ থেকে abroad এ job পাওয়ার process",
    "Work visa কিভাবে পাবো developer হিসেবে",
    "USA vs Canada vs Europe job market comparison",
    "Dubai তে developer দের demand কেমন",
    "Singapore তে tech job এর prospects",
    "Japan এ software engineer হিসেবে যাওয়ার উপায়",
    "Germany তে Blue Card program",
    "UK Global Talent Visa for tech",
    "Startup vs MNC কোথায় join করবো",
    "Company culture কেন important",
    "Toxic workplace কিভাবে identify করবো",
    "Work-life balance vs hustle culture",
    "Burnout কিভাবে avoid করবো tech industry তে",
    "Imposter syndrome কি এবং কিভাবে handle করবো",
    "Developer দের mental health",
    "Side project কি career growth এ help করে",
    "Open source contribution কি job পেতে সাহায্য করে",
    "Tech community involvement কেন important",
    "Conference এ speak করার benefit",
    "Blog লেখা কি career growth এ help করে",
    "Personal branding for developers",
    "LinkedIn এ active থাকার benefit",
    "IT sector vs non-IT sector salary comparison",
    "Contractual job vs permanent job",
    "Outsourcing company vs product company",
    "বাংলাদেশের IT industry র ভবিষ্যৎ",
    "IT industry তে layoff এর reality",
    "Recession proof career tips for developers",
    "Multiple job offers পেলে কিভাবে decide করবো",
    "First job vs dream job - কোথায় focus করবো",
    "Career change to tech - worth it or not",
    "Non-CS background থেকে developer হওয়া কি সম্ভব",
    "Bootcamp vs self-study vs university degree",
    "MBA vs tech skills কোনটা better career এ",
    "Developer advocate role কি",
    "DevRel কি নতুন career path",
]

# ========================================
# INTERVIEW PREPARATION
# ========================================
INTERVIEW_TOPICS = [
    "Technical interview এ কি কি জিজ্ঞেস করে",
    "System design interview কিভাবে prepare করবো",
    "Behavioral interview tips",
    "STAR method কি এবং কিভাবে use করবো",
    "Live coding interview এ nervous হলে কি করবো",
    "Whiteboard interview tips",
    "Take home assignment কিভাবে handle করবো",
    "Interview এ salary expectation জিজ্ঞেস করলে কি বলবো",
    "HR interview এ কি কি common questions আসে",
    "Why should we hire you - এর best answer",
    "Tell me about yourself - কিভাবে answer করবো",
    "Strength and weakness question কিভাবে handle করবো",
    "Interview এ questions ask করা কেন important",
    "Interview rejection handle করার উপায়",
    "Multiple rounds of interview কিভাবে manage করবো",
    "Group discussion interview tips",
    "Presentation round কিভাবে handle করবো",
    "Code review round এ কি expect করা হয়",
    "Culture fit interview কি",
    "Interview এ project explanation কিভাবে করবো",
    "System design interview এ কি কি cover করতে হয়",
    "Database design interview questions",
    "API design interview questions",
    "Concurrency related interview questions",
    "DP problems interview এ কেন জিজ্ঞেস করে",
    "Tree এবং graph problems interview tips",
    "Interview এ time management",
    "Mock interview কেন করা উচিত",
    "Pramp, interviewing.io কি worth it",
    "FAANG interview preparation roadmap",
    "বাংলাদেশী company গুলোতে interview process কেমন",
    "Remote job interview কিভাবে different",
    "Freelancing interview tips",
    "Contract role interview vs full-time interview",
    "Interview এ red flags",
    "Panel interview handle করার tips",
]

# ========================================
# LEARNING & EDUCATION
# ========================================
LEARNING_TOPICS = [
    "CSE তে পড়া কি এখনও ভালো decision",
    "Self-taught developer হওয়ার challenges",
    "Online course কোনগুলো সত্যিই কাজের",
    "YouTube দেখে coding শেখা কি সম্ভব",
    "Udemy vs Coursera vs freeCodeCamp",
    "Tutorial hell থেকে কিভাবে বের হবো",
    "Project based learning কেন effective",
    "Documentation পড়া কেন important",
    "Official docs vs YouTube tutorials",
    "Programming book পড়া কি এখনও দরকার",
    "Best programming books for beginners",
    "Learning roadmap কিভাবে বানাবো",
    "একসাথে অনেক কিছু শিখতে গেলে কিছুই শেখা হয় না",
    "একটা technology master করতে কতদিন লাগে",
    "Consistency কেন talent এর থেকে important",
    "প্রতিদিন কতটুকু সময় coding practice করা উচিত",
    "Morning routine for developers",
    "Night owl vs morning person - coding এ কে better",
    "Coding শেখার সময় notes নেওয়া কি দরকার",
    "Spaced repetition technique for learning",
    "Feynman technique কিভাবে coding এ apply করবো",
    "Teaching others কেন best learning method",
    "Study group vs solo learning",
    "Mentor কিভাবে খুঁজবো tech industry তে",
    "Campus placement vs off-campus job hunting",
    "University degree vs practical skills",
    "Computer Science fundamentals কি shortcut নেওয়া যায়",
    "Operating system concepts কেন জানা দরকার",
    "Networking basics every developer should know",
    "DSA শেখা কি web developer দের জন্য দরকার",
    "Math কি programming এ really লাগে",
    "English skills কেন developer দের জন্য important",
    "Technical writing skills কিভাবে improve করবো",
    "ব্লগ লেখা কিভাবে learning accelerate করে",
    "Open source contribution দিয়ে skill building",
    "Hackathon এ participate করার benefit",
    "Coding competition কি job পেতে help করে",
    "Certification কি আসলেই value add করে",
    "AWS certification কি worth the money",
    "Google certifications কেমন",
    "Bangla তে programming resource কতটুকু আছে",
    "বাংলাদেশে tech education এর বর্তমান অবস্থা",
    "Private university vs public university for CSE",
    "MSc in CS করা কি worth it",
    "PhD in Computer Science কি দরকার industry তে",
    "Continuous learning কেন tech industry তে mandatory",
    "New technology শিখতে হলে কি approach নিবো",
    "Technology stack select করার criteria",
    "Shiny object syndrome কি এবং কিভাবে avoid করবো",
    "Deep work কেন important programmer দের জন্য",
    "Focus mode কিভাবে maintain করবো coding করার সময়",
]

# ========================================
# DEVELOPER LIFE & CULTURE
# ========================================
DEV_LIFE_TOPICS = [
    "Developer life আসলে যেমন vs মানুষ যা ভাবে",
    "Coding করতে করতে রাত ৩টা বেজে গেলে",
    "Production bug fix করার pressure",
    "Friday deploy কেন করা উচিত না",
    "On-call duty র horror stories",
    "Daily standup meeting কি আসলেই productive",
    "Sprint planning কেন এত boring লাগে",
    "Jira ticket vs real work difference",
    "Manager কে technical things explain করার কষ্ট",
    "Non-technical people কে code explain করা",
    "Client এর last minute requirements change",
    "Scope creep কি এবং কিভাবে handle করবো",
    "Estimation কেন developer রা ভুল করে",
    "Meeting overload কিভাবে handle করবো",
    "Email vs Slack vs Teams communication",
    "Remote work এর advantages এবং challenges",
    "Work from home এ productivity maintain করার tips",
    "Co-working space vs home office",
    "Developer desk setup tips",
    "Ergonomic chair এবং standing desk কি worth it",
    "Monitor কয়টা use করলে productivity বাড়ে",
    "Mechanical keyboard কি productivity improve করে",
    "Coffee vs tea - developer দের preference",
    "Coding music কি focus improve করে",
    "Developer burnout এর signs",
    "Tech industry তে ageism কি reality",
    "Developer দের physical health",
    "Eye strain কিভাবে handle করবো",
    "Back pain from sitting all day",
    "Exercise routine for developers",
    "Meditation কি developer দের help করে",
    "Side project ideas for developers",
    "Weekend coding কি healthy",
    "Developer communities in Bangladesh",
    "Tech meetup এ যাওয়ার benefit",
    "Code conference কেন attend করা উচিত",
    "Developer blog শুরু করার guide",
    "Tech content creation এর challenges",
    "YouTube channel শুরু করা developer হিসেবে",
    "Developer দের social media presence",
    "LinkedIn vs Twitter for developers",
    "Developer gatekeeping কেন harmful",
    "Senior developers কেন juniors কে help করা উচিত",
    "Code ownership vs collective ownership",
    "Technical documentation লেখার importance",
    "Knowledge sharing culture in teams",
    "Developer onboarding experience",
    "First day at a new tech company",
    "Switching teams within same company",
    "WFH policy changes and developer reactions",
]

# ========================================
# INDUSTRY & TRENDS
# ========================================
INDUSTRY_TOPICS = [
    "Tech layoffs এর impact on Bangladesh",
    "বাংলাদেশের IT sector এর growth",
    "Outsourcing industry কি decline হচ্ছে",
    "Product based company কেন better",
    "SaaS business model for Bangladeshi developers",
    "Tech startup ecosystem in Dhaka",
    "International remote job market for BD developers",
    "Upwork, Fiverr এ কি আসলেই ভালো income হয়",
    "Toptal এ কিভাবে join করবো",
    "Web3 কি dead নাকি alive",
    "Blockchain development এর ভবিষ্যৎ",
    "Cryptocurrency আর coding এর connection",
    "Metaverse কি হয়ে গেল",
    "AR/VR development এর future",
    "IoT development opportunities",
    "Edge computing কি",
    "5G এর impact on software development",
    "Low code/No code কি developers replace করবে",
    "Bubble, Webflow কি traditional coding replace করবে",
    "WordPress vs custom development debate",
    "Shopify development এর scope",
    "E-commerce development trends",
    "FinTech development opportunities in Bangladesh",
    "HealthTech software development",
    "EdTech platform development",
    "Digital Bangladesh vision and IT sector",
    "Government IT projects in Bangladesh",
    "Software testing industry growth",
    "Cybersecurity job market",
    "Data Engineering vs Data Science",
    "MLOps কেন important হচ্ছে",
    "Platform engineering trend",
    "Developer experience (DX) কেন focus করা হচ্ছে",
    "Green computing এবং sustainable software",
    "Tech industry diversity and inclusion",
    "Women in tech বাংলাদেশে",
    "Tech salary transparency কেন দরকার",
    "Equity compensation কি understand করা দরকার",
    "Stock options কিভাবে কাজ করে",
    "Tech company IPO কি developer দের affect করে",
    "FAANG vs startup culture difference",
    "Unicorn companies in South Asia",
    "Indian tech industry vs Bangladeshi tech industry",
    "Offshoring vs nearshoring trends",
    "Skills-based hiring কি degree র চেয়ে important হচ্ছে",
]

# ========================================
# FREELANCING & REMOTE WORK
# ========================================
FREELANCING_TOPICS = [
    "Freelancing শুরু করার complete guide",
    "Upwork profile কিভাবে optimize করবো",
    "Fiverr এ gig কিভাবে rank করবো",
    "Freelancing এ first client কিভাবে পাবো",
    "Freelancing vs full-time job কোনটা better",
    "Freelancing এ pricing কিভাবে set করবো",
    "Hourly rate vs fixed price project",
    "Client management tips for freelancers",
    "Freelancing এ scope creep handle করার উপায়",
    "Contract কেন sign করা উচিত freelancing এ",
    "Freelancing income tax কিভাবে দিবো বাংলাদেশে",
    "International payment receive করার উপায়",
    "Payoneer vs Wise কোনটা better",
    "বাংলাদেশ থেকে dollar earning এর challenges",
    "Freelancing portfolio কিভাবে বানাবো",
    "Cold email কিভাবে লিখবো client দের জন্য",
    "LinkedIn এ freelance client কিভাবে পাবো",
    "Freelancing এ niche selection",
    "Freelancing time management tips",
    "Multiple clients handle করার strategy",
    "Freelancing burnout কিভাবে avoid করবো",
    "Remote work tools যেগুলো daily লাগে",
    "Time zone difference হ্যান্ডেল করার tips",
    "Communication skills for remote developers",
    "Video call etiquette for remote workers",
    "Remote work কি বাংলাদেশে sustainable",
    "Digital nomad lifestyle as a developer",
    "Freelancing থেকে agency building",
    "Team building for freelance agency",
    "Freelancing legal considerations in BD",
]

# ========================================
# SYSTEM DESIGN & ARCHITECTURE
# ========================================
SYSTEM_DESIGN_TOPICS = [
    "System design কেন সবার জানা উচিত",
    "Monolith to microservices migration experience",
    "Database design best practices",
    "Relational vs Document database",
    "Event sourcing কি এবং কখন use করবো",
    "CQRS pattern explained simply",
    "Message broker কেন দরকার",
    "Apache Kafka basics",
    "RabbitMQ vs Kafka কোনটা কখন",
    "Circuit breaker pattern কি",
    "Service discovery কিভাবে কাজ করে",
    "API gateway কেন important",
    "Distributed system এর challenges",
    "CAP theorem কি এবং কেন important",
    "Eventual consistency কি",
    "Strong consistency vs eventual consistency",
    "Database replication strategies",
    "Read replicas কেন use করবো",
    "Write ahead log কি",
    "Connection pooling কেন critical",
    "Load balancer কিভাবে কাজ করে",
    "Auto scaling কিভাবে setup করবো",
    "Rate limiter কিভাবে design করবো",
    "URL shortener system design",
    "Chat application system design",
    "Notification system design",
    "File storage system design",
    "Search engine কিভাবে কাজ করে",
    "Elasticsearch basics",
    "Full text search implementation",
    "Caching patterns (Write-through, Write-back)",
    "Cache invalidation strategies",
    "CDN কিভাবে design করে",
    "Video streaming platform design",
    "Social media feed design",
    "E-commerce checkout flow design",
    "Payment processing system design",
    "Idempotent API design",
    "Saga pattern for distributed transactions",
    "Two Phase Commit কি",
    "Data pipeline design",
    "ETL process কি",
    "Real-time analytics system design",
    "Logging and monitoring architecture",
    "Multi-tenant architecture",
    "Sharding strategy কখন apply করবো",
    "Consistent hashing কি",
    "Leader election algorithm",
    "Consensus algorithms (Raft, Paxos) basics",
    "Disaster recovery architecture",
]

# ========================================
# SECURITY
# ========================================
SECURITY_TOPICS = [
    "Web application security basics",
    "OWASP Top 10 কি every developer জানা উচিত",
    "SQL injection কিভাবে prevent করবো",
    "XSS attack কি এবং কিভাবে prevent করবো",
    "CSRF protection কিভাবে implement করবো",
    "Password hashing best practices",
    "Two factor authentication implement করার guide",
    "API security best practices",
    "JWT security considerations",
    "OAuth security risks",
    "SSL/TLS কিভাবে কাজ করে",
    "HTTPS কেন mandatory",
    "CORS policy setup best practices",
    "Content Security Policy কি",
    "Rate limiting for security",
    "DDoS attack prevention",
    "Data encryption at rest and in transit",
    "Secrets management best practices",
    "Environment variable security",
    "Dependency vulnerability scanning",
    "Supply chain attack কি",
    "Security audit কিভাবে করবো",
    "Penetration testing basics",
    "Bug bounty programs কি worth it",
    "Cybersecurity career path for developers",
    "Security awareness for developers",
    "Secure coding practices",
    "Privacy by design কি",
    "GDPR compliance for developers",
    "Data protection best practices",
]

# ========================================
# TESTING & QA
# ========================================
TESTING_TOPICS = [
    "Unit testing কেন important",
    "Integration testing vs unit testing",
    "End to end testing কি always দরকার",
    "Test driven development (TDD) কি worth it",
    "Testing pyramid কি",
    "Code coverage কতটুকু হলে enough",
    "Mocking and stubbing কেন দরকার",
    "Testing best practices",
    "Cypress vs Playwright কোনটা better",
    "Jest testing tips",
    "PyTest কেন popular",
    "API testing কিভাবে করবো",
    "Load testing কেন দরকার",
    "Performance testing basics",
    "Regression testing automation",
    "Manual testing vs automation testing",
    "QA engineer vs developer testing",
    "Shift left testing কি",
    "Testing in production কি করা উচিত",
    "Feature flag based testing",
    "A/B testing কিভাবে implement করবো",
    "Smoke testing vs sanity testing",
    "Test data management",
    "Testing microservices challenges",
    "Contract testing কি",
    "Visual regression testing",
    "Accessibility testing tools",
    "Mobile app testing strategy",
    "Cross browser testing tips",
    "Testing culture কিভাবে build করবো team এ",
]

# ========================================
# TOOLS & PRODUCTIVITY
# ========================================
TOOLS_TOPICS = [
    "VS Code tips and tricks",
    "VS Code extensions every developer needs",
    "Terminal customization tips",
    "Git advanced commands যেগুলো জানা দরকার",
    "Git branching strategy",
    "Git rebase vs merge debate",
    "GitFlow vs trunk based development",
    "Conventional commits কি follow করা উচিত",
    "Package manager (npm, yarn, pnpm) comparison",
    "Monorepo vs polyrepo কোনটা better",
    "Linting tools এবং code formatting",
    "Prettier এবং ESLint setup",
    "Pre-commit hooks কেন use করবো",
    "Docker for local development",
    "Postman vs Insomnia API testing tools",
    "Database client tools comparison",
    "Figma for developers",
    "Notion vs Obsidian for note taking",
    "Time tracking tools for developers",
    "Pomodoro technique কি developers দের জন্য কাজ করে",
    "Productivity apps for developers",
    "Alfred/Raycast কি Windows alternatives আছে",
    "Terminal tools (Oh My Zsh, Starship)",
    "tmux কেন শেখা উচিত",
    "Vi/Vim কি এখনও relevant",
    "Neovim vs VS Code debate",
    "JetBrains IDEs vs VS Code",
    "WebStorm কি worth the price",
    "Chrome DevTools hidden features",
    "Debugging tools every developer should know",
    "Performance profiling tools",
    "Network debugging tools",
    "Log analysis tools",
    "Slack productivity tips for developers",
    "Documentation tools (Notion, Confluence)",
    "Diagramming tools (draw.io, Excalidraw)",
    "Project management tools comparison",
    "Linear vs Jira কোনটা better",
    "GitHub features অনেকে জানে না",
    "Automation tools for developers",
]

# ========================================
# SOFT SKILLS
# ========================================
SOFT_SKILLS_TOPICS = [
    "Communication skills কেন technical skills এর চেয়ে important",
    "Technical writing কিভাবে improve করবো",
    "Presentation skills for developers",
    "Team collaboration tips",
    "Conflict resolution in tech teams",
    "Giving and receiving code review feedback",
    "Saying no to unrealistic deadlines",
    "Managing up - boss কে কিভাবে manage করবো",
    "Leadership skills for developers",
    "Mentoring junior developers",
    "Cross-functional team communication",
    "Stakeholder management for tech leads",
    "Negotiation skills for developers",
    "Public speaking for tech professionals",
    "Emotional intelligence in tech",
    "Active listening in meetings",
    "Written communication tips (email, Slack)",
    "Time management for developers",
    "Prioritization frameworks",
    "Decision making in tech",
    "Problem solving approach for complex issues",
    "Critical thinking for developers",
    "Creativity in software development",
    "Empathy in UX design",
    "Customer focus for developers",
    "Business acumen for software engineers",
    "Understanding product metrics",
    "Revenue impact of engineering decisions",
    "Building trust in remote teams",
    "Networking at tech events",
]

# ========================================
# STARTUPS & BUSINESS
# ========================================
STARTUP_TOPICS = [
    "Developer থেকে founder হওয়ার journey",
    "Side project থেকে startup বানানো",
    "MVP কি এবং কিভাবে build করবো",
    "Product Market Fit কি",
    "Startup idea validation কিভাবে করবো",
    "Solo founder vs co-founder debate",
    "Technical co-founder কি দরকার",
    "Bootstrap vs VC funding",
    "SaaS product launch করার guide",
    "Indie hacking কি",
    "Micro SaaS ideas for developers",
    "Developer tools business opportunity",
    "Open source business model",
    "Pricing strategy for SaaS products",
    "Customer acquisition for tech products",
    "Growth hacking basics for developers",
    "Content marketing for tech products",
    "SEO for developer tools",
    "Product Hunt launch strategy",
    "Startup metrics every founder should track",
    "Lean startup methodology",
    "Agile vs waterfall in startups",
    "Building in public কি",
    "Developer community building",
    "API first business model",
    "Platform business model",
    "Marketplace development challenges",
    "বাংলাদেশে tech startup funding",
    "Angel investors in Bangladesh",
    "Y Combinator application tips",
]

# ========================================
# PERSONAL GROWTH & MINDSET
# ========================================
MINDSET_TOPICS = [
    "Growth mindset vs fixed mindset programming এ",
    "Comfort zone থেকে বের হওয়ার importance",
    "Failure থেকে শেখা - developer perspective",
    "Goal setting for developers",
    "Annual review কিভাবে লিখবো tech industry তে",
    "5 year career plan কিভাবে বানাবো",
    "Developer journal রাখা কি help করে",
    "Gratitude practice for stressful tech life",
    "Comparing yourself to others on LinkedIn",
    "Social media break কি developers দের দরকার",
    "Reading habit কিভাবে build করবো",
    "Technical books vs non-technical books",
    "Podcasts for developers",
    "YouTube channels every developer should follow",
    "Newsletters worth subscribing for developers",
    "Building a second brain for developers",
    "Digital note taking system",
    "Knowledge management for developers",
    "Daily reflection habit",
    "Weekly review practice",
    "Discipline vs motivation debate",
    "Procrastination কিভাবে beat করবো",
    "Focus improvement techniques",
    "Distraction management for developers",
    "Phone addiction vs productivity",
    "Work ethic - কতটুকু কাজ করলে enough",
    "Perfectionism কেন harmful programming এ",
    "Done is better than perfect",
    "Shipping fast vs quality debate",
    "Delayed gratification in career building",
]

# ========================================
# STUDENT SPECIFIC
# ========================================
STUDENT_TOPICS = [
    "CSE admission নিয়ে ভাবছেন যারা তাদের জন্য",
    "University তে programming শেখার reality",
    "CGPA কি job পেতে important",
    "Internship কিভাবে পাবো tech company তে",
    "Resume বানানো freshers দের জন্য",
    "First project কি বানাবো portfolio তে",
    "Campus recruitment preparation",
    "University project ideas for CSE students",
    "Thesis vs project কোনটা choose করবো",
    "Research paper publish করা কি students দের দরকার",
    "Part-time job vs full-time study",
    "Freelancing while studying কি possible",
    "Study abroad for CS students",
    "GRE preparation for CS students",
    "MS in Computer Science preparation",
    "Students দের কি AI tools use করা উচিত",
    "Cheating vs learning - AI usage for students",
    "Competitive programming for students",
    "ACM ICPC preparation tips",
    "Google Summer of Code কি",
    "MLH Fellowship কি",
    "Student developer communities",
    "GitHub Student Developer Pack",
    "Free resources for CS students",
    "Summer break এ কি করবো CS student হিসেবে",
    "Final year project ideas 2025-2026",
    "Semester project management tips",
    "Online degree vs traditional degree",
    "Coding bootcamp vs university degree",
    "Students দের time management tips",
    "প্রোগ্রামিং শুরু করার best approach for beginners",
    "কোন language দিয়ে শুরু করবো",
    "Web development learning path for beginners",
    "Android vs iOS development কোনটা শিখবো",
    "Career guidance for CS freshers",
    "LinkedIn profile for students",
    "GitHub profile building for students",
    "Contributing to open source as a student",
    "Tech events for students in Bangladesh",
    "Hackathon preparation guide for beginners",
]

# ========================================
# SENIOR ENGINEER & ARCHITECTURE  
# ========================================
SENIOR_TOPICS = [
    "Senior engineer হিসেবে সবচেয়ে challenging কি",
    "Technical decision making framework",
    "Architecture Decision Records (ADR) কি",
    "Code review culture কিভাবে build করবো",
    "Team productivity কিভাবে improve করবো",
    "Technical mentorship কিভাবে দিবো",
    "Onboarding process কিভাবে improve করবো",
    "Documentation culture build করার tips",
    "Technical roadmap কিভাবে বানাবো",
    "Buy vs build decision",
    "Third party dependency management",
    "Platform team vs feature team",
    "Staff engineer expectations",
    "Architect role responsibilities",
    "Tech debt management strategy",
    "Migration planning and execution",
    "Large scale refactoring approach",
    "Performance tuning at scale",
    "Incident management process",
    "Post mortem culture",
    "On-call rotation management",
    "SLA vs SLO vs SLI",
    "Production readiness checklist",
    "Release management process",
    "Feature flag management",
    "A/B testing at scale",
    "Data driven decision making in engineering",
    "Engineering metrics that matter",
    "DORA metrics কি",
    "Developer productivity measurement",
    "Cross team collaboration challenges",
    "Stakeholder communication for tech leads",
    "Presenting technical concepts to non-technical audience",
    "Budget planning for engineering teams",
    "Vendor management for tech leaders",
    "Hiring and interviewing as a senior",
    "Building diverse engineering teams",
    "Remote team management",
    "Engineering culture কিভাবে shape করবো",
    "Innovation time allocation (20% time)",
]

# ========================================
# DEBUGGING & PROBLEM SOLVING
# ========================================
DEBUGGING_TOPICS = [
    "Production bug debugging strategy",
    "Console.log debugging কি professional",
    "Debugger tools কিভাবে effectively use করবো",
    "Memory leak detection techniques",
    "Performance profiling step by step",
    "N+1 query কিভাবে detect করবো",
    "Slow API response debugging",
    "Database query optimization",
    "Network request debugging",
    "CORS error debugging guide",
    "Port already in use error fix",
    "npm dependency conflicts resolve করার উপায়",
    "Docker container debugging",
    "Kubernetes pod crash debugging",
    "Log analysis for bug detection",
    "Error monitoring setup",
    "Sentry integration guide",
    "Stack trace reading tips",
    "Race condition কিভাবে detect করবো",
    "Deadlock debugging approach",
    "Heap dump analysis",
    "Thread dump analysis",
    "Browser rendering issue debugging",
    "CSS debugging tips",
    "Responsive design issues debugging",
    "API integration debugging",
    "Authentication flow debugging",
    "Cache related bugs",
    "Time zone related bugs",
    "Encoding issues (UTF-8) debugging",
    "Production vs development environment differences",
    "Configuration related bugs",
    "Third party service failure handling",
    "Intermittent bug detection approach",
    "Bug reproduction steps documentation",
]

# ========================================
# MOBILE DEVELOPMENT
# ========================================
MOBILE_TOPICS = [
    "React Native vs Flutter কোনটা শিখবো",
    "Flutter development এর pros and cons",
    "React Native performance issues",
    "Native vs cross-platform development",
    "iOS development শেখা কি Mac ছাড়া সম্ভব",
    "Android development with Kotlin",
    "Mobile app architecture patterns",
    "State management in mobile apps",
    "Mobile app performance optimization",
    "App Store optimization (ASO)",
    "Play Store app publishing guide",
    "Mobile app monetization strategies",
    "Push notification implementation",
    "Offline first mobile app design",
    "Mobile app security best practices",
    "Mobile API design considerations",
    "Image caching in mobile apps",
    "Mobile testing strategies",
    "Mobile CI/CD pipeline",
    "Flutter web vs React Native web",
    "Progressive Web App vs native app",
    "Mobile UX design principles",
    "Responsive design for mobile",
    "Mobile app analytics tools",
    "App crash reporting tools",
    "Mobile development trends 2025-2026",
    "Super app concept কি",
    "Mobile payment integration (bKash, Nagad)",
    "Bangla font rendering issues in mobile apps",
    "Mobile accessibility best practices",
]

# ========================================
# DATABASE & DATA
# ========================================
DATABASE_TOPICS = [
    "SQL basics every developer must know",
    "PostgreSQL advanced features",
    "MySQL vs PostgreSQL detailed comparison",
    "MongoDB schema design best practices",
    "Redis use cases beyond caching",
    "Database normalization কি এবং কখন করবো",
    "Database denormalization কখন acceptable",
    "Index কিভাবে কাজ করে",
    "Composite index কখন use করবো",
    "Query optimization techniques",
    "Explain plan পড়া শেখা",
    "Database connection pooling best practices",
    "Database migration strategy",
    "Database backup and recovery",
    "Point in time recovery কি",
    "Database replication setup",
    "Master slave architecture",
    "Multi-region database setup",
    "Database monitoring tools",
    "Slow query log analysis",
    "Transaction isolation levels",
    "ACID properties explained simply",
    "BASE vs ACID কখন কোনটা",
    "Time series database কি (InfluxDB, TimescaleDB)",
    "Graph database (Neo4j) কখন use করবো",
    "Column-oriented database (Cassandra) কি",
    "Database per service pattern in microservices",
    "Data warehouse vs data lake",
    "ETL pipeline design",
    "Data modeling best practices",
]

# ========================================
# VERSION CONTROL & COLLABORATION
# ========================================
GIT_TOPICS = [
    "Git কেন শেখা mandatory every developer এর",
    "Git basic commands cheat sheet",
    "Git branching model কিভাবে follow করবো",
    "Git merge conflict resolve করার tips",
    "Git rebase কখন use করবো",
    "Git stash কিভাবে effectively use করবো",
    "Git cherry-pick কি",
    "Git bisect দিয়ে bug finding",
    "Git hooks কি এবং কিভাবে setup করবো",
    "Conventional commits কেন follow করবো",
    "Semantic versioning কি",
    "Git flow vs GitHub flow",
    "Pull request best practices",
    "Code review best practices",
    "Merge queue কি",
    "Protected branches setup",
    "GitHub Actions getting started",
    "GitHub Projects for project management",
    "GitHub Copilot tips and tricks",
    "GitLab vs GitHub comparison",
    "Bitbucket কি এখনও relevant",
    "Monorepo management with Git",
    "Git LFS কি এবং কখন দরকার",
    "Git submodules explained",
    ".gitignore best practices",
]

# ========================================
# TECH PHILOSOPHY & OPINIONS
# ========================================
PHILOSOPHY_TOPICS = [
    "Perfect code বলে কি কিছু আছে",
    "Premature optimization কেন evil",
    "Over-engineering কিভাবে avoid করবো",
    "Simple code vs clever code",
    "Readable code কেন smart code এর চেয়ে better",
    "YAGNI principle কি",
    "Convention over configuration",
    "Composition over inheritance",
    "Pragmatic programming কি",
    "Software craftsmanship কি dead",
    "10x developer myth",
    "Rockstar developer culture কেন toxic",
    "Meritocracy in tech কি reality",
    "Open source sustainability problem",
    "Free software vs open source debate",
    "Privacy vs convenience trade-off",
    "Ethical technology development",
    "Technology addiction এবং responsibility",
    "Dark patterns in UX",
    "Move fast and break things কি এখনও valid",
    "Technical excellence vs business value",
    "Engineering culture vs sales culture",
    "Developer experience কেন matter করে",
    "Technology choices এবং their consequences",
    "Hype driven development কেন harmful",
    "Resume driven development কি",
    "Cargo cult programming কি",
    "Bike shedding কি",
    "NIH (Not Invented Here) syndrome",
    "Second system effect কি",
]

# ========================================
# BANGLADESHI TECH SCENE
# ========================================
BD_TECH_TOPICS = [
    "বাংলাদেশের IT sector কোথায় যাচ্ছে",
    "বাংলাদেশে software company গুলোর culture",
    "Dhaka vs remote work for BD developers",
    "বাংলাদেশী developers দের international market এ competition",
    "বাংলাদেশ থেকে silicon valley level work",
    "Local tech community building in Bangladesh",
    "Tech events এবং conferences in Bangladesh",
    "বাংলাদেশে freelancing industry",
    "IT park কি বাংলাদেশের IT sector কে boost করবে",
    "বাংলাদেশের IT পলিসি কি developer friendly",
    "Payment gateway challenges in Bangladesh",
    "bKash, Nagad integration for developers",
    "বাংলাদেশে tech startup funding challenges",
    "Bangladeshi developer communities online",
    "Stack Learner community impact",
    "বাংলাদেশে software engineering education quality",
    "বাংলাদেশের CSE graduates employability",
    "Brain drain - BD developers going abroad",
    "Returning to BD after working abroad in tech",
    "বাংলাদেশে remote job availability",
    "Dollar rate impact on freelancers in BD",
    "Dual currency card for BD developers",
    "Upwork/Fiverr account issues for Bangladeshi",
    "Internet infrastructure in Bangladesh for developers",
    "Power outage impact on developer productivity",
    "Co-working spaces in Dhaka for developers",
    "Tech hubs in Bangladesh outside Dhaka",
    "Women in tech scene in Bangladesh",
    "বাংলায় tech content creation",
    "Bangla programming resources quality",
]

# ========================================
# PROJECT IDEAS & CHALLENGES
# ========================================
PROJECT_TOPICS = [
    "Portfolio project ideas for beginners",
    "Full stack project ideas for practice",
    "API project ideas for backend developers",
    "Machine learning project ideas",
    "Mobile app project ideas",
    "30 days coding challenge ideas",
    "Weekend project ideas for developers",
    "Open source project contribution guide",
    "Clone project বানানো কি beneficial",
    "পছন্দের app clone করে learning",
    "E-commerce project building guide",
    "Social media clone project",
    "Chat application building guide",
    "Blog platform building from scratch",
    "Task management app building",
    "Weather app building as first project",
    "URL shortener project guide",
    "REST API project ideas",
    "Real-time application project ideas",
    "Personal finance tracker app",
    "Habit tracker app building",
    "Developer portfolio website ideas",
    "Landing page design project",
    "Dashboard project building",
    "Chrome extension project ideas",
    "VS Code extension building",
    "CLI tool building for fun",
    "Automation script project ideas",
    "Web scraping project ideas",
    "Telegram/Discord bot building",
]

# ========================================
# CODE QUALITY & BEST PRACTICES
# ========================================
CODE_QUALITY_TOPICS = [
    "Code review কেন seriously নেওয়া উচিত",
    "Clean architecture কি",
    "Hexagonal architecture explained",
    "Domain driven design basics",
    "Dependency injection কি এবং কেন দরকার",
    "Separation of concerns principle",
    "Single responsibility principle real examples",
    "Open/Closed principle explained",
    "Liskov substitution principle কি",
    "Interface segregation principle",
    "Code coupling vs cohesion",
    "Code complexity measurement",
    "Cyclomatic complexity কি",
    "Code duplication কেন harmful",
    "Magic numbers কি এবং কেন avoid করবো",
    "Naming conventions for different languages",
    "File structure organization best practices",
    "Configuration management",
    "Feature flags implementation",
    "Backward compatibility কেন maintain করবো",
    "API breaking changes handle করার উপায়",
    "Deprecation strategy",
    "Changelog maintaining best practices",
    "Semantic release automation",
    "Code linting importance",
    "Static analysis tools",
    "Code formatter setup guide",
    "EditorConfig কি এবং কেন use করবো",
    "Code standards documentation",
    "Engineering handbook কেন বানাবো",
]

# ========================================
# AGILE & PROJECT MANAGEMENT
# ========================================
AGILE_TOPICS = [
    "Agile vs Waterfall তুলনা",
    "Scrum framework explained simply",
    "Kanban board কিভাবে use করবো",
    "Sprint planning কিভাবে effectively করবো",
    "Sprint retrospective কেন important",
    "Daily standup কি আসলেই productive",
    "User stories কিভাবে লিখবো",
    "Story points estimation",
    "Velocity tracking কি meaningful",
    "Burndown chart কি",
    "Product backlog management",
    "Technical stories vs user stories",
    "Bug tracking best practices",
    "Release planning approach",
    "Continuous delivery vs continuous deployment",
    "Feature prioritization frameworks (RICE, MoSCoW)",
    "Scope management tips",
    "Stakeholder management for developers",
    "Project deadline কিভাবে meet করবো",
    "Time estimation কেন developers ভুল করে",
    "Meeting fatigue কিভাবে avoid করবো",
    "Async communication benefits",
    "Documentation driven development",
    "Technical specification writing guide",
    "RFC (Request for Comments) process",
]

# ========================================
# EMERGING TECH
# ========================================
EMERGING_TOPICS = [
    "Quantum computing basics for developers",
    "Edge computing applications",
    "Serverless computing কি future",
    "WebAssembly কি browser এর future",
    "Rust in systems programming",
    "Zig language কি C replace করবে",
    "Bun vs Node.js vs Deno",
    "WASM outside browser",
    "Ambient computing কি",
    "Brain computer interface development",
    "AR glasses development",
    "Spatial computing কি",
    "3D web development (Three.js)",
    "Game development with web technologies",
    "Procedural generation কি",
    "Digital twin technology",
    "Smart contract development",
    "Zero knowledge proofs কি",
    "Decentralized applications (dApps)",
    "AI code generation tools comparison",
    "Autonomous AI agents development",
    "Multi-modal AI applications",
    "Voice interface development",
    "Computer vision applications development",
    "Robotics programming basics",
    "Drone programming",
    "Embedded systems development",
    "Real-time OS (RTOS) basics",
    "WebGPU কি WebGL replace করবে",
    "Progressive enhancement vs graceful degradation",
]

# ========================================
# MOTIVATION & REAL TALK
# ========================================
REAL_TALK_TOPICS = [
    "Programming শেখা ছেড়ে দিতে চাইলে কি করবো",
    "Frustration handle করার উপায় coding এ",
    "একা একা coding শিখছি - motivate কিভাবে থাকবো",
    "Coding এ ব্যর্থ হওয়ার পর আবার শুরু করা",
    "Developer হিসেবে imposter syndrome handle করা",
    "Senior developer ও কি imposter feel করে",
    "Programming এ talent vs hard work",
    "Age কি matter করে programming শেখায়",
    "30 বছর বয়সে কি programming শুরু করা যায়",
    "Non-CS background থেকে developer হওয়ার reality",
    "Programming শেখার সময় যে ভুলগুলো করেছিলাম",
    "First job পাওয়ার journey - আমার অভিজ্ঞতা",
    "Job rejection handle করার মানসিক প্রস্তুতি",
    "Salary comparison করা কি healthy",
    "Peers দের সাথে compare করলে কি হয়",
    "Developer life lonely হতে পারে",
    "Work-life balance কি সত্যিই possible tech এ",
    "Passion vs paycheck debate",
    "Boring work vs exciting work in tech",
    "Job satisfaction কিভাবে পাবো tech industry তে",
    "Career pivot করার courage",
    "Risk নেওয়ার importance career এ",
    "ছোট company vs বড় company experience",
    "First salary র memories",
    "Coding journey শুরু করার best time কি",
    "Technology কি মানুষকে isolated করছে",
    "Screen time management for tech workers",
    "Hobbies outside of coding",
    "Developer দের relationship challenges",
    "Family কে developer life explain করা",
]

# ========================================
# CLOUD SERVICES & DEPLOYMENT
# ========================================
CLOUD_TOPICS = [
    "AWS for beginners guide",
    "Cloud computing কি সহজ ভাষায়",
    "EC2 vs Lambda কখন কোনটা",
    "S3 storage best practices",
    "RDS vs self-managed database",
    "DynamoDB কখন use করবো",
    "Azure DevOps getting started",
    "Google Cloud Platform basics",
    "Cloud provider selection criteria",
    "Multi-cloud strategy কি worth it",
    "Cloud security best practices",
    "Cloud cost monitoring tools",
    "Reserved instances vs on-demand",
    "Spot instances কখন use করবো",
    "Cloud networking basics (VPC, subnet)",
    "CloudFormation vs Terraform",
    "Serverless framework getting started",
    "Firebase for web developers",
    "Supabase getting started guide",
    "PlanetScale database advantages",
    "Vercel deployment for Next.js",
    "Railway deployment guide",
    "Render vs Railway vs Fly.io",
    "DigitalOcean for small projects",
    "Cloud Functions best practices",
    "API Gateway setup guide",
    "CloudWatch monitoring basics",
    "S3 vs CloudFront optimization",
    "Auto-scaling configuration guide",
    "Container registry management",
]

# ========================================
# UI/UX & DESIGN
# ========================================
DESIGN_TOPICS = [
    "Developer দের কি UI/UX জানা দরকার",
    "Design thinking কি",
    "User research basics for developers",
    "Wireframing tools comparison",
    "Figma basics for developers",
    "Color theory for web developers",
    "Typography basics for web",
    "Layout design principles",
    "White space কেন important design এ",
    "Mobile first design approach",
    "Responsive vs adaptive design",
    "Accessibility (a11y) basics",
    "Dark mode design considerations",
    "Design system কি এবং কেন দরকার",
    "Component library building",
    "Storybook কি এবং কিভাবে use করবো",
    "Animation in web design",
    "Micro-interactions কি",
    "Loading state design patterns",
    "Error state design best practices",
    "Empty state design",
    "Onboarding flow design",
    "Navigation patterns for web apps",
    "Form design best practices",
    "Data visualization basics",
    "Dashboard design principles",
    "Landing page conversion tips",
    "CTA button design best practices",
    "Icon selection and usage tips",
    "Image and illustration usage in web",
]


# ===================================================
# ALL TOPICS COMBINED
# ===================================================
ALL_TOPICS = (
    PROGRAMMING_TOPICS +
    WEB_DEV_TOPICS +
    BACKEND_TOPICS +
    DEVOPS_TOPICS +
    AI_ML_TOPICS +
    CAREER_TOPICS +
    INTERVIEW_TOPICS +
    LEARNING_TOPICS +
    DEV_LIFE_TOPICS +
    INDUSTRY_TOPICS +
    FREELANCING_TOPICS +
    SYSTEM_DESIGN_TOPICS +
    SECURITY_TOPICS +
    TESTING_TOPICS +
    TOOLS_TOPICS +
    SOFT_SKILLS_TOPICS +
    STARTUP_TOPICS +
    MINDSET_TOPICS +
    STUDENT_TOPICS +
    SENIOR_TOPICS +
    DEBUGGING_TOPICS +
    MOBILE_TOPICS +
    DATABASE_TOPICS +
    GIT_TOPICS +
    PHILOSOPHY_TOPICS +
    BD_TECH_TOPICS +
    PROJECT_TOPICS +
    CODE_QUALITY_TOPICS +
    AGILE_TOPICS +
    EMERGING_TOPICS +
    REAL_TALK_TOPICS +
    CLOUD_TOPICS +
    DESIGN_TOPICS
)

# Category mapping for analytics
TOPIC_CATEGORIES = {
    "Programming & Coding": PROGRAMMING_TOPICS,
    "Web Development": WEB_DEV_TOPICS,
    "Backend Development": BACKEND_TOPICS,
    "DevOps & Cloud": DEVOPS_TOPICS,
    "AI & Machine Learning": AI_ML_TOPICS,
    "Career & Jobs": CAREER_TOPICS,
    "Interview Preparation": INTERVIEW_TOPICS,
    "Learning & Education": LEARNING_TOPICS,
    "Developer Life": DEV_LIFE_TOPICS,
    "Industry & Trends": INDUSTRY_TOPICS,
    "Freelancing & Remote": FREELANCING_TOPICS,
    "System Design": SYSTEM_DESIGN_TOPICS,
    "Security": SECURITY_TOPICS,
    "Testing & QA": TESTING_TOPICS,
    "Tools & Productivity": TOOLS_TOPICS,
    "Soft Skills": SOFT_SKILLS_TOPICS,
    "Startups & Business": STARTUP_TOPICS,
    "Personal Growth": MINDSET_TOPICS,
    "Student Life": STUDENT_TOPICS,
    "Senior Engineering": SENIOR_TOPICS,
    "Debugging": DEBUGGING_TOPICS,
    "Mobile Development": MOBILE_TOPICS,
    "Database & Data": DATABASE_TOPICS,
    "Git & Collaboration": GIT_TOPICS,
    "Tech Philosophy": PHILOSOPHY_TOPICS,
    "Bangladesh Tech": BD_TECH_TOPICS,
    "Project Ideas": PROJECT_TOPICS,
    "Code Quality": CODE_QUALITY_TOPICS,
    "Agile & PM": AGILE_TOPICS,
    "Emerging Tech": EMERGING_TOPICS,
    "Real Talk": REAL_TALK_TOPICS,
    "Cloud Services": CLOUD_TOPICS,
    "UI/UX Design": DESIGN_TOPICS,
}

def get_random_topic() -> str:
    """Get a random topic from all topics"""
    return random.choice(ALL_TOPICS)

def get_random_topic_from_category(category: str) -> str:
    """Get a random topic from a specific category"""
    topics = TOPIC_CATEGORIES.get(category, ALL_TOPICS)
    return random.choice(topics)

def get_all_categories() -> list:
    """Get all available categories"""
    return list(TOPIC_CATEGORIES.keys())

def get_topic_count() -> int:
    """Get total number of unique topics"""
    return len(set(ALL_TOPICS))


import random
